# 03 - Deep Learning Segmentation Model

This notebook implements the deep learning approach for dendrite segmentation in SEM images.

A YOLO segmentation model is trained using the labeled dataset exported from Roboflow.  
The dataset contains polygon annotations of dendrite regions and is organized into **train / validation / test** splits.

Because the Roboflow free tier does not allow downloading the trained model weights (`best.pt`), the model is trained locally using the **Ultralytics YOLO framework** in order to obtain the weights required for inference and evaluation.

The objectives of this notebook are:

- Train a YOLO segmentation model on the dendrite dataset
- Save the trained model weights (`best.pt`)
- Run inference on the test images
- Generate predicted segmentation masks

The generated predictions will later be compared against:

- Ground Truth annotations  
- The Classical Segmentation Pipeline results  

Evaluation metrics used for comparison include:

- IoU (Intersection over Union)
- Dice coefficient
- Precision
- Recall

This enables a quantitative comparison between **classical image processing methods** and **deep learning based segmentation** for dendrite detection.

### Dataset Structure

The dataset is organized in YOLO segmentation format and contains
three splits:

- **train** - images used for training
- **valid** - images used for validation
- **test** - images used for evaluation

Each image has a corresponding label file containing polygon annotations
that describe the dendritic structures.

In [4]:
from pathlib import Path

DATASET_ROOT = Path("dataset/SEM_Dendrite_Segmentation_v2.v3i.yolov11")
DATA_YAML = DATASET_ROOT / "data.yaml"

print("Dataset root exists:", DATASET_ROOT.exists())
print("data.yaml exists:", DATA_YAML.exists())

Dataset root exists: True
data.yaml exists: True

### Training Configuration

The model is trained using the following parameters:

- **Epochs:** 50
- **Image size:** 640 × 640
- **Batch size:** 4
- **Task:** Instance segmentation

During training, the network learns to predict segmentation masks
for dendritic structures in SEM images.

In [ ]:
from ultralytics import YOLO

model = YOLO("yolo11n-seg.pt")

results = model.train(
    data=str(DATA_YAML),
    epochs=50,
    imgsz=640,
    batch=4,
    project="runs_local",
    name="dendrite_seg",
    pretrained=True
)

Ultralytics 8.4.21  Python-3.12.7 torch-2.10.0+cpu CPU (12th Gen Intel Core i7-1255U)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=dataset\SEM_Dendrite_Segmentation_v2.v3i.yolov11\data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=dendrite_seg, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_local, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\sara tuvian\Desktop\   \ \notebooks\runs\segment\runs_local\dendrite_seg, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    683635  ultralytics.nn.modules.head.Segment          [1, 32, 64, 16, None, [64, 128, 256]]
YOLO11n-seg summary: 204 layers, 2,842,803 parameters, 2,842,787 gradients, 9.7 GFLOPs

Transferred 510/561 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
train: Fast image access  (ping: 0.10.0 ms, read: 176.045.2 MB/s, size: 75.7 KB)
train: Scanning C:\Users\sara tuvian\Desktop\עיבוד תמונה ולמידה עמוקה\פרויקט סוף\notebooks\dataset\SEM_Dendrite_Segmentation_v2.v3i.yolov11\train\labels.cache... 10 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 10/10  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 164.594.4 MB/s, size: 97.2 KB)
val: Scanning C:\Users\sara tuvian\Desktop\עיבוד תמונה ולמידה עמוקה\פרויקט סוף\notebooks\dataset\SEM_Dendrite_Segmentation_v2.v3i.yolov11\valid\labels.cache... 2 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2/2  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 90 weight(decay=0.0), 101 weight(decay=0.0005), 100 bias(decay=0.0)
Plotting labels to C:\Users\sara tuvian\Desktop\   \ \notebooks\runs\segment\runs_local\dendrite_seg\labels.jpg...
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to C:\Users\sara tuvian\Desktop\   \ \notebooks\runs\segment\runs_local\dendrite_seg
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       1/50         0G      2.712      5.185      3.343      1.598          0        113        640: 100% ━━━━━━━━━━━━ 3/3 3.7s/it 11.2s5.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0s/it 2.0s
                   all          2        602    0.00833    0.00831    0.00916    0.00457    0.00333    0.00332    0.00184   0.000452

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       2/50         0G      2.379      4.367      3.376      1.334          0        197        640: 100% ━━━━━━━━━━━━ 3/3 3.9s/it 11.8s5.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0183     0.0183     0.0146    0.00827     0.0133     0.0133     0.0118    0.00365

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       3/50         0G      2.464      4.104      3.327      1.254          0        362        640: 100% ━━━━━━━━━━━━ 3/3 4.5s/it 13.5s7.0s5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0233     0.0233     0.0176     0.0085     0.0183     0.0183     0.0144    0.00472

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       4/50         0G      2.259      4.225      3.156      1.286          0         60        640: 100% ━━━━━━━━━━━━ 3/3 3.6s/it 10.9s4.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602      0.025     0.0249     0.0191     0.0103     0.0233     0.0233     0.0169    0.00535

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       5/50         0G      2.396      3.906      3.177      1.217          0        185        640: 100% ━━━━━━━━━━━━ 3/3 3.9s/it 11.6s5.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0s/it 2.0s
                   all          2        602     0.0283     0.0282     0.0225     0.0111       0.02     0.0199     0.0182    0.00648

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       6/50         0G      2.444      4.046      3.107      1.178          0        751        640: 100% ━━━━━━━━━━━━ 3/3 4.4s/it 13.2s7.1s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0s/it 2.0s
                   all          2        602     0.0383     0.0382     0.0294     0.0148       0.03     0.0299     0.0239    0.00845

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       7/50         0G      2.014      3.554      2.966      1.072          0        520        640: 100% ━━━━━━━━━━━━ 3/3 3.7s/it 11.1s6.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.3s/it 2.3s
                   all          2        602     0.0367     0.0365     0.0293     0.0162     0.0333     0.0332     0.0282     0.0104

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       8/50         0G      2.206      3.644      3.031      1.081          0        540        640: 100% ━━━━━━━━━━━━ 3/3 4.8s/it 14.4s8.2s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.2s/it 2.2s
                   all          2        602     0.0267     0.0266     0.0289     0.0123       0.03     0.0299     0.0236    0.00863

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       9/50         0G      2.053      3.449      2.886      1.073          0         84        640: 100% ━━━━━━━━━━━━ 3/3 4.0s/it 12.1s4.8s9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0267     0.0266     0.0289     0.0123       0.03     0.0299     0.0236    0.00863

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      10/50         0G      2.037      3.284      2.822      1.094          0        105        640: 100% ━━━━━━━━━━━━ 3/3 3.9s/it 11.6s5.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0317     0.0316     0.0275     0.0117     0.0283     0.0282     0.0221    0.00852

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      11/50         0G       2.07      3.195      2.756      1.036          0        164        640: 100% ━━━━━━━━━━━━ 3/3 4.6s/it 13.7s6.2s5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0317     0.0316     0.0275     0.0117     0.0283     0.0282     0.0221    0.00852

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      12/50         0G      2.322      3.377      2.643      1.127          0        182        640: 100% ━━━━━━━━━━━━ 3/3 3.9s/it 11.7s5.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602      0.035     0.0349     0.0307     0.0133     0.0417     0.0415     0.0301    0.00867

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      13/50         0G      2.041      3.031      2.562      1.016          0        158        640: 100% ━━━━━━━━━━━━ 3/3 3.8s/it 11.5s5.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.2s/it 2.2s
                   all          2        602      0.035     0.0349     0.0307     0.0133     0.0417     0.0415     0.0301    0.00867

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      14/50         0G      2.405      3.429      2.625      1.091          0        269        640: 100% ━━━━━━━━━━━━ 3/3 4.4s/it 13.2s6.3s1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.4s/it 2.4s
                   all          2        602      0.045     0.0449     0.0352     0.0159     0.0533     0.0532     0.0361     0.0112

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      15/50         0G      2.499      3.327       2.58      1.073          0        399        640: 100% ━━━━━━━━━━━━ 3/3 3.8s/it 11.5s5.9ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602      0.045     0.0449     0.0352     0.0159     0.0533     0.0532     0.0361     0.0112

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      16/50         0G      2.217        3.1      2.457      1.051          0        947        640: 100% ━━━━━━━━━━━━ 3/3 3.7s/it 11.2s6.7ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0s/it 2.0s
                   all          2        602      0.045     0.0449     0.0352     0.0159     0.0533     0.0532     0.0361     0.0112

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      17/50         0G      2.335       3.24      2.505      1.067          0         90        640: 100% ━━━━━━━━━━━━ 3/3 4.4s/it 13.3s5.0s6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.2s/it 2.2s
                   all          2        602     0.0517     0.0515     0.0378     0.0205     0.0667     0.0664     0.0411     0.0163

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      18/50         0G       2.36      3.292      2.336      1.056          0        341        640: 100% ━━━━━━━━━━━━ 3/3 4.2s/it 12.5s7.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.5s/it 2.5s
                   all          2        602     0.0517     0.0515     0.0378     0.0205     0.0667     0.0664     0.0411     0.0163

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      19/50         0G      2.497      3.212      2.469      1.067          0        519        640: 100% ━━━━━━━━━━━━ 3/3 4.8s/it 14.4s6.9s3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0s/it 2.0s
                   all          2        602     0.0517     0.0515     0.0378     0.0205     0.0667     0.0664     0.0411     0.0163

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      20/50         0G       2.31      3.098      2.373       1.03          0        291        640: 100% ━━━━━━━━━━━━ 3/3 4.2s/it 12.5s5.8ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0367     0.0365     0.0299     0.0148     0.0517     0.0515     0.0368     0.0137

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      21/50         0G      2.473      3.242      2.416      1.047          0        619        640: 100% ━━━━━━━━━━━━ 3/3 4.9s/it 14.7s7.2s5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0367     0.0365     0.0299     0.0148     0.0517     0.0515     0.0368     0.0137

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      22/50         0G      2.252      3.034      2.125      1.097          0         67        640: 100% ━━━━━━━━━━━━ 3/3 4.0s/it 11.9s5.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.2s/it 2.2s
                   all          2        602     0.0367     0.0365     0.0299     0.0148     0.0517     0.0515     0.0368     0.0137

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      23/50         0G      2.212      3.033      2.221      1.064          0        209        640: 100% ━━━━━━━━━━━━ 3/3 3.8s/it 11.5s5.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0367     0.0365     0.0299     0.0148     0.0517     0.0515     0.0368     0.0137

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      24/50         0G      2.216      3.039       2.25      1.027          0        775        640: 100% ━━━━━━━━━━━━ 3/3 4.1s/it 12.3s7.4ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.1s/it 2.1s
                   all          2        602     0.0567     0.0565     0.0462     0.0251     0.0617     0.0615     0.0473     0.0151

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      25/50         0G      2.376      3.151      2.177      1.035          0        304        640: 100% ━━━━━━━━━━━━ 3/3 4.3s/it 13.0s6.1s9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0s/it 2.0s
                   all          2        602     0.0567     0.0565     0.0462     0.0251     0.0617     0.0615     0.0473     0.0151

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      26/50         0G      2.207      2.941       2.08      1.054          0        257        640: 100% ━━━━━━━━━━━━ 3/3 3.7s/it 11.1s5.9ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.0s/it 2.0s
                   all          2        602     0.0567     0.0565     0.0462     0.0251     0.0617     0.0615     0.0473     0.0151

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size

### Training2 Configuration

The final deep learning model was trained using the following parameters:

- **Model:** YOLOv11s-seg
- **Epochs:** 150
- **Image size:** 640 × 640
- **Batch size:** 4
- **Task:** Instance segmentation
- **Initialization:** Pretrained weights (transfer learning)

During training, the network learns to predict segmentation masks for dendritic structures in SEM images.

This configuration provides higher model capacity compared to the initial YOLOv11n model and improves segmentation performance on complex dendritic structures.

In [8]:
from ultralytics import YOLO

model = YOLO("yolo11s-seg.pt")

results = model.train(
    data=str(DATA_YAML),
    epochs=150,
    imgsz=640,
    batch=4,
    device="cpu",
    augment=True,
    project="runs_local",
    name="dendrite_seg_s"
)

Ultralytics 8.4.21  Python-3.12.7 torch-2.10.0+cpu CPU (12th Gen Intel Core i7-1255U)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=True, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=dataset\SEM_Dendrite_Segmentation_v2.v3i.yolov11\data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11s-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=dendrite_seg_s, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_local, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\sara tuvian\Desktop\   \ \notebooks\runs\segment\runs_local\dendrite_seg_s, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1   1474291  ultralytics.nn.modules.head.Segment          [1, 32, 128, 16, None, [128, 256, 512]]
YOLO11s-seg summary: 204 layers, 10,082,675 parameters, 10,082,659 gradients, 33.1 GFLOPs

Transferred 555/561 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
train: Fast image access  (ping: 0.10.1 ms, read: 69.525.0 MB/s, size: 75.7 KB)
train: Scanning C:\Users\sara tuvian\Desktop\עיבוד תמונה ולמידה עמוקה\פרויקט סוף\notebooks\dataset\SEM_Dendrite_Segmentation_v2.v3i.yolov11\train\labels.cache... 10 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 10/10  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 76.714.4 MB/s, size: 97.2 KB)
val: Scanning C:\Users\sara tuvian\Desktop\עיבוד תמונה ולמידה עמוקה\פרויקט סוף\notebooks\dataset\SEM_Dendrite_Segmentation_v2.v3i.yolov11\valid\labels.cache... 2 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2/2  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 90 weight(decay=0.0), 101 weight(decay=0.0005), 100 bias(decay=0.0)
Plotting labels to C:\Users\sara tuvian\Desktop\   \ \notebooks\runs\segment\runs_local\dendrite_seg_s\labels.jpg...
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to C:\Users\sara tuvian\Desktop\   \ \notebooks\runs\segment\runs_local\dendrite_seg_s
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      1/150         0G      2.979      5.117      2.947      1.707          0        113        640: 100% ━━━━━━━━━━━━ 3/3 6.6s/it 19.7s9.8s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8s/it 2.8s
                   all          2        602      0.109     0.0714     0.0536     0.0216      0.104     0.0714     0.0497     0.0146

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      2/150         0G      2.477       4.17      2.489      1.386          0        197        640: 100% ━━━━━━━━━━━━ 3/3 6.3s/it 18.9s<10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8s/it 2.8s
                   all          2        602      0.221     0.0847     0.0892     0.0379      0.173     0.0963     0.0782     0.0252

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      3/150         0G      2.212      3.715      1.914      1.212          0        362        640: 100% ━━━━━━━━━━━━ 3/3 6.6s/it 19.8s<10.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.5s/it 3.5s
                   all          2        602       0.17     0.0963     0.0928     0.0416      0.172      0.101     0.0867     0.0255

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      4/150         0G      1.958      3.608      1.882      1.206          0         60        640: 100% ━━━━━━━━━━━━ 3/3 6.6s/it 19.8s9.0s7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0s/it 3.0s
                   all          2        602      0.159       0.11     0.0908     0.0447      0.153      0.116     0.0909     0.0294

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      5/150         0G      2.146      3.309      1.732      1.171          0        185        640: 100% ━━━━━━━━━━━━ 3/3 6.8s/it 20.5s<10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0s/it 3.0s
                   all          2        602       0.22      0.103      0.103     0.0496      0.157     0.0864     0.0873     0.0279

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      6/150         0G      2.177      3.629      1.577      1.125          0        751        640: 100% ━━━━━━━━━━━━ 3/3 7.1s/it 21.2s<11.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8s/it 2.8s
                   all          2        602      0.207     0.0864      0.083     0.0388      0.109     0.0897     0.0624     0.0187

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      7/150         0G      1.858      3.398      1.464      1.047          0        520        640: 100% ━━━━━━━━━━━━ 3/3 6.1s/it 18.3s<10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0s/it 3.0s
                   all          2        602      0.259      0.106       0.12      0.061      0.184       0.13      0.118     0.0411

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      8/150         0G      2.066      3.513       1.34      1.075          0        540        640: 100% ━━━━━━━━━━━━ 3/3 6.6s/it 19.7s<10.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.7s/it 2.7s
                   all          2        602      0.256     0.0963      0.116     0.0569      0.132     0.0963     0.0837     0.0268

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      9/150         0G       1.83      2.979      1.505       1.07          0         84        640: 100% ━━━━━━━━━━━━ 3/3 6.5s/it 19.4s9.1s8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9s/it 2.9s
                   all          2        602      0.256     0.0963      0.116     0.0569      0.132     0.0963     0.0837     0.0268

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     10/150         0G      1.853      2.932      1.321      1.067          0        105        640: 100% ━━━━━━━━━━━━ 3/3 6.3s/it 18.8s9.3s8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8s/it 2.8s
                   all          2        602      0.183      0.111      0.116      0.059      0.151      0.098     0.0953     0.0324

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     11/150         0G      1.899      2.894      1.384      1.026          0        164        640: 100% ━━━━━━━━━━━━ 3/3 6.7s/it 20.2s9.8s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0s/it 3.0s
                   all          2        602      0.183      0.111      0.116      0.059      0.151      0.098     0.0953     0.0324

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     12/150         0G      2.116      3.139      1.593      1.108          0        182        640: 100% ━━━━━━━━━━━━ 3/3 6.1s/it 18.3s8.8s6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9s/it 2.9s
                   all          2        602       0.28      0.101       0.13      0.061      0.175     0.0897     0.0939     0.0358

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     13/150         0G      1.759      2.728      1.303      1.022          0        158        640: 100% ━━━━━━━━━━━━ 3/3 6.0s/it 18.1s9.4s9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9s/it 2.9s
                   all          2        602       0.28      0.101       0.13      0.061      0.175     0.0897     0.0939     0.0358

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     14/150         0G      2.088      3.148      1.383       1.06          0        269        640: 100% ━━━━━━━━━━━━ 3/3 6.7s/it 20.0s<10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8s/it 2.8s
                   all          2        602      0.151      0.105     0.0961     0.0433      0.155      0.154      0.112     0.0452

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     15/150         0G      2.322      2.982      1.389      1.099          0        399        640: 100% ━━━━━━━━━━━━ 3/3 6.3s/it 19.0s9.9s7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0s/it 3.0s
                   all          2        602      0.151      0.105     0.0961     0.0433      0.155      0.154      0.112     0.0452

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     16/150         0G      1.997      2.863      1.381      1.048          0        947        640: 100% ━━━━━━━━━━━━ 3/3 6.5s/it 19.6s<10.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9s/it 2.9s
                   all          2        602      0.151      0.105     0.0961     0.0433      0.155      0.154      0.112     0.0452

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     17/150         0G      2.216      2.931      1.623      1.122          0         90        640: 100% ━━━━━━━━━━━━ 3/3 6.7s/it 20.1s9.0s1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8s/it 2.8s
                   all          2        602      0.228      0.163       0.14     0.0593      0.228      0.206      0.147     0.0611

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     18/150         0G      2.297       3.03       1.48      1.105          0        341        640: 100% ━━━━━━━━━━━━ 3/3 6.4s/it 19.1s9.9s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0s/it 3.0s
                   all          2        602      0.228      0.163       0.14     0.0593      0.228      0.206      0.147     0.0611

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     19/150         0G      2.308      2.867      1.394      1.077          0        519        640: 100% ━━━━━━━━━━━━ 3/3 6.9s/it 20.8s<10.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9s/it 2.9s
                   all          2        602      0.228      0.163       0.14     0.0593      0.228      0.206      0.147     0.0611

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     20/150         0G      2.201      2.908      1.404      1.071          0        291        640: 100% ━━━━━━━━━━━━ 3/3 6.7s/it 20.0s9.9s6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0s/it 3.0s
                   all          2        602      0.232      0.176      0.163      0.069      0.159      0.101     0.0761     0.0321

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     21/150         0G      2.432      3.493      1.297      1.053          0        619        640: 100% ━━━━━━━━━━━━ 3/3 7.2s/it 21.5s<11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.1s/it 3.1s
                   all          2        602      0.232      0.176      0.163      0.069      0.159      0.101     0.0761     0.0321

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     22/150         0G       2.03       3.05      1.408      1.107          0         67        640: 100% ━━━━━━━━━━━━ 3/3 6.1s/it 18.3s8.7s4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9s/it 2.9s
                   all          2        602      0.232      0.176      0.163      0.069      0.159      0.101     0.0761     0.0321

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     23/150         0G      2.079      3.242      1.297      1.076          0        209        640: 100% ━━━━━━━━━━━━ 3/3 6.3s/it 18.8s9.4s9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.1s/it 3.1s
                   all          2        602      0.232      0.176      0.163      0.069      0.159      0.101     0.0761     0.0321

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     24/150         0G       2.17      3.184      1.298      1.067          0        775        640: 100% ━━━━━━━━━━━━ 3/3 6.6s/it 19.9s<11.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.9s/it 2.9s
                   all          2        602      0.213       0.13      0.125       0.06      0.234      0.201      0.156     0.0649

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     25/150         0G      2.092      3.791      1.328      1.078          0        304        640: 100% ━━━━━━━━━━━━ 3/3 6.8s/it 20.4s<10.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 2.8s/it 2.8s
                   all          2        602      0.213       0.13      0.125       0.06      0.234      0.201      0.156     0.0649

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
     26/150         0G      1.939      3.567      1.585      1.112          0        257        640: 100% ━━━━━━━━━━━━ 3/3 6.2s/it 18.7s<10.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 3.0s/it 3.0s
                   all          2        602      0.213       0.13      0.125       0.06      0.234      0.201      0.156     0.0649


### Training Results

Two training configurations were tested during the deep learning stage.

An initial model based on **YOLOv11n-seg** was trained as a baseline.  
While this lightweight model successfully detected some dendritic structures, its segmentation accuracy was limited due to the small model capacity and the complexity of the SEM images.

To improve performance, a second model using **YOLOv11s-seg** was trained for more epochs.  
This configuration achieved higher Precision, Recall, and mAP scores and produced more stable segmentation masks.

Based on these results, **YOLOv11s-seg was selected as the final deep learning model for the project**.

### Training Output

After training is completed, the best model weights are saved locally as:

`runs_local/dendrite_seg/weights/best.pt`

These weights represent the trained segmentation model
and will be used for inference and evaluation.

In [ ]:
from ultralytics import YOLO

BEST_MODEL = Path("runs/segment/runs_local/dendrite_seg_s/weights/best.pt")

print("Best model exists:", BEST_MODEL.exists())
print(BEST_MODEL)

best_model = YOLO(str(BEST_MODEL))

Best model exists: True
runs\segment\runs_local\dendrite_seg_s\weights\best.pt

In [42]:
pred_easy = best_model.predict(
    source="datasets/for_annotation/easy",
    save=True,
    project="runs_local",
    name="predict_easy",
    imgsz=640,
    conf=0.2,
    iou=0.5,
    retina_masks=True,
    show_labels=False,
    show_conf=False,
    show_boxes=False
)

image 1/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\easy\Ag_1e-8_007.png: 448x640 62 dendritess, 469.5ms
image 2/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\easy\Ag_1e-8_008.png: 448x640 50 dendritess, 454.9ms
image 3/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\easy\Ag_1e-8_009.png: 448x640 76 dendritess, 1915.2ms
image 4/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\easy\Ag_1e-8_010.png: 448x640 248 dendritess, 309.7ms
image 5/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\easy\Ag_1e-8_011.png: 448x640 300 dendritess, 222.4ms
image 6/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\easy\Ag_1e-8_012.png: 448x640 40 dendritess, 421.4ms
image 7/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\easy\Ag_1e-8_017.png: 448x640 298 dendritess, 336.2ms
Speed: 26.5ms preprocess, 589.9ms inference, 1779.4ms postprocess per image at shape (1, 3, 448, 640)
Results saved to C:\Users\sara tuvian\Desktop\   \ \notebooks\runs\segment\runs_local\predict_easy

In [43]:
pred_hard = best_model.predict(
    source="datasets/for_annotation/hard",
    save=True,
    project="runs_local",
    name="predict_hard",
    imgsz=640,
    conf=0.2,
    iou=0.5,
    retina_masks=True,
    show_labels=False,
    show_conf=False,
    show_boxes=False
)

image 1/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\hard\70nm_R_50nm_pitch_ETD_001.png: 448x640 41 dendritess, 381.6ms
image 2/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\hard\70nm_R_50nm_pitch_ETD_002.png: 448x640 135 dendritess, 294.3ms
image 3/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\hard\70nm_R_50nm_pitch_ETD_003.png: 448x640 164 dendritess, 251.4ms
image 4/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\hard\70nm_R_50nm_pitch_ETD_004.png: 448x640 76 dendritess, 271.4ms
image 5/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\hard\70nm_R_50nm_pitch_ETD_005.png: 448x640 30 dendritess, 221.0ms
image 6/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\hard\70nm_R_50nm_pitch_ETD_006.png: 448x640 29 dendritess, 225.0ms
image 7/7 c:\Users\sara tuvian\Desktop\   \ \notebooks\datasets\for_annotation\hard\ETD_097.png: 448x640 17 dendritess, 220.4ms
Speed: 6.2ms preprocess, 266.4ms inference, 521.6ms postprocess per image at shape (1, 3, 448, 640)
Results saved to C:\Users\sara tuvian\Desktop\   \ \notebooks\runs\segment\runs_local\predict_hard

### Model Performance Summary

Two YOLO segmentation models were trained during the development of the deep learning pipeline.

The first model used the **YOLO11n-seg architecture** and was trained for **50 epochs**. While the model was able to detect some dendritic structures, the segmentation quality and detection consistency were limited due to the small model capacity and short training duration.

To improve performance, a second model based on **YOLO11s-seg** was trained for **150 epochs**. This model has a larger architecture and allows better feature learning from the dataset.

After training, the best model from the second experiment was applied to images from both the **EASY** and **HARD** subsets in order to evaluate its ability to detect dendritic structures.

Visual inspection of the predictions shows that the model is able to detect many dendritic branches across the images. In the EASY images, the detected masks generally follow the main dendritic structures well. In the HARD images, detection becomes more challenging due to higher noise levels and the presence of thin, low-contrast dendrites.

Although some **false detections** and **missed structures** remain, the model is still able to identify a significant portion of the dendritic patterns.

These results demonstrate that deep learning–based instance segmentation can successfully detect dendritic structures in SEM images, even when the training dataset is relatively small. Further improvements could likely be achieved by expanding the dataset, refining annotations, and performing additional training or hyperparameter tuning.

## Export YOLO Binary Masks

The following cell extracts binary segmentation masks from the YOLO prediction results and saves them to disk.

For each image, all predicted instance masks are merged into a single binary mask.

The masks are saved separately for the **EASY** and **HARD** subsets under:

- `runs/segment/runs_local/yolo_binary_masks/easy`
- `runs/segment/runs_local/yolo_binary_masks/hard`

In [44]:
from pathlib import Path
import numpy as np
import cv2

# --------------------------------------------------
# Output folders
# --------------------------------------------------
BASE_OUT = Path("runs/segment/runs_local/yolo_binary_masks")
EASY_OUT = BASE_OUT / "easy"
HARD_OUT = BASE_OUT / "hard"

EASY_OUT.mkdir(parents=True, exist_ok=True)
HARD_OUT.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------
# Helper function
# --------------------------------------------------
def export_combined_masks(pred_results, out_dir: Path, threshold: float = 0.5):
    saved = 0

    for r in pred_results:
        img_path = Path(r.path)
        img = cv2.imread(str(img_path))
        if img is None:
            print(f"Skipping unreadable image: {img_path}")
            continue

        h, w = img.shape[:2]
        combined_mask = np.zeros((h, w), dtype=np.uint8)

        if r.masks is not None:
            masks = r.masks.data.cpu().numpy()

            for m in masks:
                m_bin = (m > threshold).astype(np.uint8)
                m_bin = cv2.resize(m_bin, (w, h), interpolation=cv2.INTER_NEAREST)
                combined_mask = np.maximum(combined_mask, m_bin)

        out_path = out_dir / f"{img_path.stem}_yolo_mask.png"
        cv2.imwrite(str(out_path), combined_mask * 255)
        saved += 1

    return saved

# --------------------------------------------------
# Export masks
# --------------------------------------------------
easy_saved = export_combined_masks(pred_easy, EASY_OUT)
hard_saved = export_combined_masks(pred_hard, HARD_OUT)

print(f"EASY masks saved: {easy_saved} -> {EASY_OUT}")
print(f"HARD masks saved: {hard_saved} -> {HARD_OUT}")

EASY masks saved: 7 -> runs\segment\runs_local\yolo_binary_masks\easy
HARD masks saved: 7 -> runs\segment\runs_local\yolo_binary_masks\hard

### Training Metrics

During training, YOLO logs performance metrics for each epoch.
The following table shows the training progress recorded in `results.csv`.

Key metrics include:

- **Precision** - proportion of correct detections
- **Recall** - proportion of detected dendrites
- **mAP50** - detection accuracy at IoU threshold 0.5
- **Segmentation mAP** - segmentation quality across IoU thresholds

These metrics help evaluate whether the model improves during training.

In [45]:
import pandas as pd

RESULTS_PATH = Path("runs/segment/runs_local/dendrite_seg_s/results.csv")

results_df = pd.read_csv(RESULTS_PATH)

results_df.head()

,epoch,time,train/box_loss,train/seg_loss,train/cls_loss,train/dfl_loss,train/sem_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),...,metrics/mAP50(M),metrics/mAP50-95(M),val/box_loss,val/seg_loss,val/cls_loss,val/dfl_loss,val/sem_loss,lr/pg0,lr/pg1,lr/pg2
0,1,22.6424,2.97863,5.11718,2.94694,1.70682,0,0.10851,0.07143,0.05363,...,0.04966,0.01461,2.97678,4.47107,2.41709,1.32099,0,0.000040,0.000040,0.000040
1,2,46.7866,2.47742,4.17000,2.48944,1.38556,0,0.22099,0.08472,0.08924,...,0.07823,0.02523,2.63671,3.90545,3.99390,1.24690,0,0.000099,0.000099,0.000099
2,3,71.0072,2.21248,3.71496,1.91360,1.21222,0,0.16990,0.09635,0.09277,...,0.08670,0.02549,2.48052,3.86546,5.23019,1.19923,0,0.000158,0.000158,0.000158
3,4,95.0173,1.95763,3.60820,1.88153,1.20560,0,0.15896,0.10963,0.09082,...,0.09090,0.02938,2.37882,3.84394,3.25326,1.15284,0,0.000216,0.000216,0.000216
4,5,119.3940,2.14561,3.30938,1.73218,1.17098,0,0.22015,0.10299,0.10310,...,0.08732,0.02792,2.36666,3.69846,3.09547,1.13495,0,0.000273,0.000273,0.000273

In [46]:
results_df.tail(1)

,epoch,time,train/box_loss,train/seg_loss,train/cls_loss,train/dfl_loss,train/sem_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),...,metrics/mAP50(M),metrics/mAP50-95(M),val/box_loss,val/seg_loss,val/cls_loss,val/dfl_loss,val/sem_loss,lr/pg0,lr/pg1,lr/pg2
149,150,3561.29,1.60141,2.34072,0.98705,0.93227,0,0.34078,0.2309,0.22228,...,0.21991,0.09326,2.30443,2.75868,1.35745,0.97174,0,0.000033,0.000033,0.000033

In [47]:
results_df[[
    "epoch",
    "metrics/precision(M)",
    "metrics/recall(M)",
    "metrics/mAP50(M)",
    "metrics/mAP50-95(M)"
]].tail()

,epoch,metrics/precision(M),metrics/recall(M),metrics/mAP50(M),metrics/mAP50-95(M)
145,146,0.35731,0.25083,0.21991,0.09326
146,147,0.35731,0.25083,0.21991,0.09326
147,148,0.35731,0.25083,0.21991,0.09326
148,149,0.35731,0.25083,0.21991,0.09326
149,150,0.35731,0.25083,0.21991,0.09326

### Training Results Analysis

The YOLO segmentation model was trained for **150 epochs** on the annotated SEM dendrite dataset using the **YOLO11s segmentation architecture**.

During training, the model progressively improved as the training losses decreased and the evaluation metrics stabilized toward the final epochs.

At the final stage of training, the model achieved the following **segmentation performance**:

- **Precision (Segmentation):** 0.357  
- **Recall (Segmentation):** 0.251  
- **mAP@0.5:** 0.220  
- **mAP@0.5:0.95:** 0.093  

These results indicate that the model successfully learned meaningful dendritic structures from the training data. Although the performance is moderate, the model is able to identify multiple dendritic branches across the images.

The relatively limited performance is expected due to several factors:

- the **small dataset size** (14 SEM images)
- the **high level of noise** present in SEM microscopy images
- the **complex branching morphology** of dendritic structures
- the presence of **thin and low-contrast dendrites** in the HARD subset

Despite these challenges, the trained model demonstrates the ability to detect dendritic regions and generate segmentation masks that follow the main dendritic structures.

### Conclusion

In this notebook, a **YOLO-based instance segmentation approach** was developed to detect dendritic structures in SEM microscopy images.

Two YOLO segmentation models were trained during the experimentation phase. The initial model used the **YOLO11n-seg architecture trained for 50 epochs**, while the improved model used the **YOLO11s-seg architecture trained for 150 epochs**, which provided better learning capacity and more stable results.

The final model was trained locally using the annotated dataset and evaluated on both the **Easy** and **Hard** image subsets.

The training metrics and prediction examples demonstrate that the model can learn meaningful dendritic patterns even from a relatively small dataset. The model is capable of identifying multiple dendritic branches within complex SEM images.

However, the segmentation quality is still influenced by noise and structural complexity, particularly in the **HARD images**, where dendrites are thinner and less distinct.

Overall, the results demonstrate that **deep learning–based segmentation using YOLO can detect dendritic structures in SEM images**, even with limited training data.

In the next stage of the project, the deep learning approach will be **compared with the classical image processing pipeline** developed earlier in order to evaluate the strengths and limitations of each method.